---
- hosts: inventory
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt: upgrade=yes update_cache=yes cache_valid_time=86400

  tasks:
  - name: Установить curl
    yum:
    name: "{{ package }}"
    vars:
      package:
      - curl
      state: latest
  tasks:
     - name: Start service firewalld, if not started
       ansible.builtin.service:
       name: firewalld
       state: started
  tasks:
  - name: Разрешение 80 8080 1834 порта - firewalld
  hosts: test_servers
  become_method: sudo
  become_user: root

  tasks:
  - name: Разрешим 80 порт
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: enabled
  tasks:
  - name: Разрешим 8080 TCP порт
    ansible.posix.firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
  tasks:
  - name: Разрешим 1834 TCP порт
    ansible.posix.firewalld:
      port: 1834/tcp
      permanent: yes
      state: enabled
  tasks:
  - name: Перезапустим service firewalld на всех узлах
    ansible.builtin.service:
      name: firewalld
      state: restarted
  tasks:
  - name: Изменение SSH порта
  hosts: all
  gather_facts: false
  vars:
    custom_ssh_port: 1834
  tasks:
    - name: test default ssh port
      local_action: wait_for port=22 timeout=5 host={{inventory_hostname}}
      register: default_ssh
      ignore_errors: true
    - name: set ansible_ssh_port to default
      set_fact: ansible_ssh_port=22
     when: default_ssh.elapsed < 5
    - name: test ssh on high port
      local_action: wait_for port={{custom_ssh_port}} timeout=5 host={{inventory_hostname}}
      register: high_ssh
      when: default_ssh.elapsed >= 5
      ignore_errors: true
    - name: set ansible_ssh_port high
      set_fact: ansible_ssh_port={{custom_ssh_port}}
      when: default_ssh.elapsed >= 5 and high_ssh.elapsed < 5
  tasks:
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
  tasks:
  - name: Install docker-compose
    remote_user: ubuntu
    get_url:
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
  tasks:
  - name: Creates directory
    file:
       path: /skillcloud-nginx
       state: directory
  tasks:
  - name: For wsr files
    remote_user: ubuntu
    get_url:
      url : https://github.com/Jeniston14/wsr-skillcloud
      dest: /skillcloud-nginx
      mode: 'u+x,g+x'

  tasks:
  - name: Перезапустим service firewalld на всех узлах
    ansible.builtin.service:
      name: firewalld
      state: restarted

  tasks:
  - name: Stop and Start ssh
    service:
      name: ssh
      state: restarted

  tasks:
  - name: Unconditionally reboot the machine with all defaults
    reboot:
      
                                          
